version: "3.9"

services:
  db:
    image: mariadb
    container_name: Data_Base
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - cangrownet

  nginx:
    image: nginx
    container_name: Nginx_LoadBalance
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
    - db
    networks:
      - cangrownet

  wordpress1:
    container_name: wordpress1
    depends_on:
    - nginx
    image: wordpress
    volumes:
    - wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - cangrownet

  wordpress2:
    container_name: wordpress2
    depends_on:
    - nginx
    image: wordpress:latest
    volumes:
    - wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - cangrownet

volumes:
    db_data: {}
    wordpress_data: {}

networks:
  cangrownet:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.20.0.0/28"
                gateway: "172.20.0.1"


